package com.finnetwork.models;// default package
// Generated Sep 13, 2017 10:47:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "fin_network")
public class Role implements java.io.Serializable {

	private int id;
	private String role;

	public Role() {
	}

	public Role(int id) {
		this.id = id;
	}

	public Role(int id, String role) {
		this.id = id;
		this.role = role;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "role", length = 25)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
